Repository kalviumcommunity/S63_AnujGoyal_IntervueX, pull requests merged in 2025-06, with the labels that each got.

#38 update changes
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Pages/Home.jsx
  client/src/Pages/Profile.jsx
  client/src/Pages/Welcome.jsx
  client/src/components/Welcome.jsx
  client/src/index.css
Labels: Review effort 4/5

#40 Add Google OAuth implementation
  FINAL_SETUP_GUIDE.md
  GOOGLE_OAUTH_SETUP.md
  backend/.env.example
  check-env.js
  create-env.js
  debug-server.js
  fix-env.js
  setup-env.sh
  setup-google-oauth.bat
  test-complete-oauth.js
  test-env-loading.js
  test-server.js
Labels: Review effort 3/5, Possible security concern

#42 adding contact page
  client/src/App.jsx
  client/src/Pages/Contact.jsx
Labels: Review effort 2/5

#44 added about page content
  client/src/App.jsx
  client/src/Pages/About.jsx
Labels: Review effort 2/5

#48 Implementing file upload funtionality
  FILE_UPLOAD_IMPLEMENTATION.md
  FINAL_SETUP_GUIDE.md
  backend/bash.exe.stackdump
  backend/controllers/user.controllers.js
  backend/middlewares/isAuthenticated.js
  backend/middlewares/multer.js
  backend/routes/user.route.js
  check-env.js
  client/src/Pages/Profile.jsx
  create-env.js
  debug-server.js
  fix-env.js
  setup-env.sh
  setup-google-oauth.bat
  test-complete-oauth.js
  test-env-loading.js
  test-server.js
Labels: Review effort 4/5, Possible security concern
